version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: metabrainnetwork
    ports:
      - "1337:1337"
      - "4000:85"
    depends_on:
      - redis
    networks:
      - redis
    volumes:
        - "/data:/data"
  redis:
    image: redis
    networks:
      - redis

networks:
  redis:
    driver: bridge
