version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: metabrainnetwork
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    depends_on:
      - redis
    networks:
      - redis
    volumes:
        - "/data:/data"
  redis:
    image: redis
    networks:
      - redis

networks:
  redis:
    driver: bridge
